language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: h2nKk5vEcU3d8NvrBhSSmgrz9s/FQFINy/8a2JQScaiYL5aSW82APmqaGSj8Tt4Zt+Su4SXZveL/QuisJoauoWJr2uSjCsfkC8Tggitlh5nn7qCn8qf+r30+bGy+keFAf5hS2P8USw0NwRAeqm21iybIigBprsKgbQMGYtcVnzRr//e1HR0SyD7tXoly82q9AJCi4k59xGaNjILrCQrLixW8pl2RwYVt4wvL2Y2g7wocpoE/8Lo0zn9VNxrrQ5ioBDyLfIS9pI0aiQf5UNspY86GtXUHVGvaUJcYmdgJylOcNmSGkX6f+2IIfrDLVnaEgh7bWvsn1cnuZuBNzYGiHVNac+mA71aS8q7CXIxR1x+Iz3n89A7GZMJUZbnw+mIFvXfFd9cyC1enod/NjrXv1iWUgJwBXcz+Ni8iYMjv7ArQmGtkpm9XUceE+mgkV9LLGdd+tIWh7z8t84ZEjX9JpwpGqWWkeChdjFYSK6nNP9FhN5QzRgK5mHmiDVtjdB8BlOw6wGsIIShw+wgtb6aRZvnN36Auy0KXZbDxHTLdBfWmUNz3geZQ72ahxr/jmLfkg7yHaFcbZvXJXwj8+fo8RCN/26aYGcQ7XDaIVdWU7oeZ9wkUbfuxQaQaFOICs/qG/hHkJ2TlQLHuxVp7VFNpDWvZ95nWRhdJrEd88z+ysDA=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-jspm
