language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: fjJyyDado8pG2kdUZeOEnnN13FrOweJTTAwkWgb+RdN6h9RaxkgLH6nwh0ZQrIs50SIMXP6tYS+vdgIo7wtnamOz4hGu3GMklF9HWGpe07aGripyjP72tl9CwyaDJlah8Nmt02W1ELEQiDAvzt85zVbJtwI6Jq4FUA3E1fSs7NyQddgU1ZOxYUbfB9Z91xoi6hPrNMRqHca70t4TcQAwOVQlJqZN73J1/5ErAbOB6QEMKr8G3L/GcJZq+a73KxtKKX8aH4NAeieSkGB/FiA/uv7V4RDzdFxCzph+Y+wfoWDGLAu6znHtfN833MQlJWrlB57mSpdJpAKTzi03xT+vOK1LKplneJdzFjBonx4E23IRz0hB1LbBuXISfFgHBEfa7JLVzAZ2QNma+2xnSFw8frcxypFsQ1ZoOGZ2pnfWlmrNMBfaID4D9p3+hBLtg9zYcJM5t2rp/NJW5yCOFsbWVzxlMWUUR2ODxPhDS05KISIhZMyQbodzZ5j/MCGNSRPPvU0dhXss2C6bP4rMaaimn6AZaurxb4rT4FaYObpT3YO5pLj07Z5nM8k5aS2pgBHbrb+4RSzAN1S9Y45g4Ufdyjz9Ys1pI5XRHciFb18xl1VFNGbgEG0xGfEf18xH4sEV16PxlKjJocCi1GSwfjIOXljMjctgYd7oFSgfQfKaTR8=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-jspm
